# **List Dua Dimensi**
List dua dimensi pada umumnya adalah menempatkan list di dalam list. 
Penggambarannya seperti sebuah matriks. 
Berikut adalah contoh dari penggunaan List Dua Dimensi

In [ ]:
#deklarasikan sebuah matriks a berikut : 
matriks_a = [
    [2,4,6,8], 
    [10,12,14,16]
]
matriks_b = [
    [1,3,5,7], 
    [9,11,13,15]
]
print(matriks_a + matriks_b)
#ini akan menghasilkan nilai berupa vektor baris dan bukan berupa matriks 
#ini juga tidak akan menghasilkan penjumlahan dari dua matriks yang sudah 
#dimasukkan melainkan hanya menggabungkan elemen-elemen dari matriks-matriks itu

[[2, 4, 6, 8], [10, 12, 14, 16], [1, 3, 5, 7], [9, 11, 13, 15]]


In [ ]:
matriks_a = [
    [2,4,6,8], 
    [10,12,14,16]
]
matriks_b = [
    [1,3,5,7], 
    [9,11,13,15]
]
for x in range(0,len(matriks_a)):
#ini untuk menentukan panjang atau ukuran matriksnya
  for y in range(0,len(matriks_a[0])):
  #ini untuk menghasilkan kolom pada matriks
  #ini dipakai 0 ataupun 1 hasilnya tetap sama
    print(matriks_a[x][y]+matriks_b[x][y])
    #perhatikan posisi-posisi seperti ini karena pada python dia bisa saja error
    #jika posisinya tidak sesuai dan komputer tidak dapat membacanya dengan benar
#ini adalah kode untuk menjumlahkan kedua buah matriks yang telah dideklarasikan
#matriks ini tidak berbentuk matriks akan tetapi hasilnya sudah sesuai
#untuk menghasilkan dia sebagai matriks, itu ada kode lainnya dan materi kita
#belum sampai disana

3
7
11
15
19
23
27
31


In [ ]:
#ini adalah contoh error karena posisi dari penggunaan for dan printnya tidak 
#jelas sehingga tidak dapat dibaca oleh sistem dengan baik
matriks_a = [
    [2,4,6,8], 
    [10,12,14,16]
]
matriks_b = [
    [1,3,5,7], 
    [9,11,13,15]
]
for x in range(0,len(matriks_a)):
for y in range(0,len(matriks_a[0])):
print(matriks_a[x][y]+matriks_b[x][y])

IndentationError: ignored

In [3]:
#untuk membuat list jadwal perkuliahan
mata_kuliah_mesin = [
    ["kalkulus"], 
    ["aljabar"],
    ["fisika"],
    ["menggambar mesin"],
]
hari = [
    ["senin"],
    ["selasa"],
    ["rabu"], 
    ["libur"]
]
for x in range(0,len(hari)):
#ini untuk menentukan panjang atau ukuran matriksnya
  for y in range(0,len(mata_kuliah_mesin[0])):
  #ini untuk menghasilkan kolom pada matriks
  #ini dipakai 0 ataupun 1 hasilnya tetap sama
    print(hari[x][y] + " " + mata_kuliah_mesin [x] [y])


senin kalkulus
selasa aljabar
rabu fisika
libur menggambar mesin


In [ ]:
mata_kuliah_mesin[0]
#ini seperti materi sebelumnya yaitu untuk mencari data di indeks ke 0 

['kalkulus']

In [ ]:
hari[1][0]
#ini untuk mencari urutan atau indeks juga dari matriks yaitu baris indeks 1 dan
#kolom indeks ke-0 

'selasa'

In [ ]:
hari[2][1]
#ini error karena data yang kita punya cuma punya kolom 1 dan indeksnya itu 
#adalah 0 (sesuai dengan penjelasan indeks di python)

IndexError: ignored

In [ ]:
hari + mata_kuliah_mesin
#ini juga dapat dipakai untuk memanggil semua data di list yang kita punya

[['senin'],
 ['selasa'],
 ['rabu'],
 ['libur'],
 ['kalkulus'],
 ['aljabar'],
 ['fisika'],
 ['menggambar mesin']]

In [5]:
for baris in mata_kuliah_mesin :
  print(baris)
  for kolom in mata_kuliah_mesin :
    print(kolom)
  #perintah ini digunakan untuk memanggil anggota dari list dua dimensi

['kalkulus']
['kalkulus']
['aljabar']
['fisika']
['menggambar mesin']
['aljabar']
['kalkulus']
['aljabar']
['fisika']
['menggambar mesin']
['fisika']
['kalkulus']
['aljabar']
['fisika']
['menggambar mesin']
['menggambar mesin']
['kalkulus']
['aljabar']
['fisika']
['menggambar mesin']


# **Tuples**

Tuples ini mirip dengan list hanya saja untuk tuples kita tidak dapat merubah isi atau anggota yang ada di dalamnya. berbeda dengan list yang bisa kita perintahkan untuk merubah atau menambahkan anggota lainnya. Adapun contoh penggunaan tuples yaitu :

In [ ]:
# deklarasikan dulu data yang kita punya 
nilai = (75,89,85,80,87,90,95,97,98,100)
print(nilai[0]

75


In [ ]:
print(nilai[0:5])
#perintah ini untuk menampilkan indeks 0 hingga ke-4 saja

(75, 89, 85, 80, 87)


In [ ]:
for isi in nilai[0:7] :
  print(isi)
#ini juga untuk menampilkan data dari indeks ke-0 sampai indeks ke-6

75
89
85
80
87
90
95


In [ ]:
nilai.append(55)

AttributeError: ignored

In [ ]:
nilai.remove(75)

AttributeError: ignored

In [ ]:
nilai.count(75)
#ini untuk mengetahui ada berapa jumlah data dari nilai yang kita input

1

In [ ]:
nilai.count()
#ini error karena sistem tidak tahu nilai apa yang ingin dihitung jumlahnya

TypeError: ignored

In [ ]:
nilai.index(75)
#ini berarti nilai 75 merupakan indeks ke-0 pada data yang kita punya

0

In [ ]:
nilai.count(10)
#ini karena nilai 10 tidak ada di data yang telah dideklarasikan sebelumnya

0

# **Dictionaries**

Dictionaries diibaratkan seperti perpustakaan dari data-data yang kita miliki. Dictionaries digunakan apabila data-data tersebut saling terkait satu sama lainnya. Data seperti identitas dan riwayat hidup seseorang merupakan salah satu contoh dari penggunaan dictionaries. Berikut adalah contoh kode dari dictionaries : 

In [ ]:
#deklarasikan terlebih dahulu data yang kita punya
identitas_43 = {
    "nama" : "Ni Putu Dina Agustina",
    "umur" : 19, 
    "gender" : "Perempuan",
    "apakah single?" : False 
}

In [ ]:
print(identitas_43["nama"])
#ini merupakan format untuk menggunakan dictionaries

Ni Putu Dina Agustina


In [ ]:
print(identitas_43["umur"])
#ini merupakan contoh yang lain terkait penggunaan dictionaries

19


In [ ]:
print(identitas_43.get("nama"))
#ini juga merupakan format lain untuk menggunaakan dictionaries

Ni Putu Dina Agustina


In [ ]:
print(identitas_43.get("Nama"))
#ini berarti dalam dictionaries tadi tidak dideklarasikan untuk variabel Nama
#karena yang digunakan adalah "nama" bukan "Nama" sehingga maknanya akan beda

None


In [ ]:
print(identitas_43.get("tanggal_lahir"))
#ini tidak ada dalam dictionaries karena tidak kita deklarasikan sebelumnya

None


In [ ]:
print(identitas_43.get("tanggal_lahir","21-11-2003"))
#ini untuk menambahkan tanggal lahirnya 

21-11-2003


In [9]:
#deklarasikan data-data berikut : 
#salah satu contoh untuk menjadikan data angka menjadi huruf 
identitas_angka= {
    "0" : "nol",
    "1" : "satu",
    "2" : "dua", 
    "3" : "tiga",  
    "4" : "empat",
    "5" : "lima",
    "6" : "enam", 
    "7" : "tujuh", 
    "8" : "delapan",
    "9" : "sembilan"
}

In [14]:
#contoh untuk data yang diinputkan sendiri
NIM_Peserta = input("Masukkan NIM Anda : ")
nomor_angka = " "
for isi in NIM_Peserta :
  nomor_angka +=identitas_angka.get(isi) + " "
print(nomor_angka)

Masukkan NIM Anda : 2208541043
 dua dua nol delapan lima empat satu nol empat tiga 


In [17]:
#contoh untuk penggunaan data yang sudah dideklarasikan
Nim = "2205531035" 
nomor_angka = " "
for isi in Nim :
  nomor_angka +=identitas_angka.get(isi) + " "
print(nomor_angka)

 dua dua nol lima lima tiga satu nol tiga lima 


# **Fungsi Dalam Python**

Fungsi pada python merupakan bagian atau blok program yang memiliki tugas tertentu. Adapun beberapa jenis fungsi seperti fungsi input, print, len, range dan sebagainya termasuk rumus-rumus dalam matematika. 

Ada dua jenis tugas fungsi pada python yaitu :
1. Menjalankan perintah
2. Menampilkan hasil perhitungan

Untuk pengunaan fungsi pada python dapat dilihat melalui contoh-contoh berikut ini :

In [43]:
#menjalankan perintah input dan print
#penggunaan \n untuk enter atau membuat baris baru 
nama = input("Masukkan nama Anda : ")
matkul = input("Masukkan jadwal Mata Kuliah Anda hari ini : ")
print("Selamat datang" + " " +nama + "\n" + "Semangat mengikuti mata kuliah " + matkul + " hari ini!")

Masukkan nama Anda : Dina
Masukkan jadwal Mata Kuliah Anda hari ini : Algoritma
Selamat datang Dina
Semangat mengikuti mata kuliah Algoritma hari ini!


In [18]:
a = input("masukkan panjang alas segitiga  :")
t = input("masukkan tinggi segitiga :")
luas_segitiga = 0.5 * float(a) * float(t)
print("Luas Segitiga adalah :",luas_segitiga)
#kode ini akan menghasilkan angka-angka di belakang koma dikarenakan menggunakan
#tipe data numerik float

masukkan panjang alas segitiga  :4
masukkan tinggi segitiga :6
Luas Segitiga adalah : 12.0


In [29]:
nama_depan = input("Masukkan nama depan Anda : ")
nama_belakang = input("Masukkan nama belakang Anda : ")
full_name = nama_depan +" "+ nama_belakang
print(full_name)

Masukkan nama depan Anda : Gede Ardi
Masukkan nama belakang Anda : Wedyantara
Gede Ardi Wedyantara


In [41]:
string = ""

x = int(input("Masukkan angka :"))
bar = x
# Looping Baris
while bar >= 0:

	# Looping Kolom Spasi Kosong
	kol = bar
	while kol > 0:
		string = string + "   "
		kol = kol - 1
	
	# Looping Kolom Bintang	
	kanan = 1
	while kanan < (x - (bar-1)):
		string = string + " * "
		kanan = kanan + 1		
		
	string = string + "\n"
	bar = bar - 1
	
print (string)

Masukkan angka :8
                        
                      * 
                   *  * 
                *  *  * 
             *  *  *  * 
          *  *  *  *  * 
       *  *  *  *  *  * 
    *  *  *  *  *  *  * 
 *  *  *  *  *  *  *  * 



In [44]:
#deklarasikan terlebih dahulu data yang kita miliki
#untuk angka yang diinputkan bertipe float yaitu mencakup bil desimal
print('##  Program Python Menghitung Luas Trapesium  ##')
print('================================================')
print()
  
sisi_atas = float(input('Input panjang sisi sejajar atas: '))
sisi_bawah = float(input('Input panjang sisi sejajar bawah: '))
tinggi = float(input('Input tinggi trapesium: '))
 
luas = 0.5 * (sisi_atas + sisi_bawah) * tinggi;
 
print('Luas trapesium =',round(luas,2))

##  Program Python Menghitung Luas Trapesium  ##

Input panjang sisi sejajar atas: 6.5
Input panjang sisi sejajar bawah: 7.8
Input tinggi trapesium: 2
Luas trapesium = 14.3


In [45]:
def jarak_tempuh(kecepatan,waktu):
  jarak_tempuh = kecepatan*waktu
  print(jarak_tempuh)
#ini untuk mendefinisikan variabel dan rumusnya

In [47]:
jarak_tempuh(100,30)
#ini adalah jarak yang ditempuh berdasarkan rumus yang dimasukkan

3000


In [65]:
#mendefinisikan variabel yang diperlukan untuk mencari luas persegi panjang
#ini digunakan untuk menginputkan data sendiri
panjang = float(input('Input panjang persegi panjang : '))
lebar = float(input('Input lebar persegi panjang : '))
luas_persegi_panjang = panjang*lebar
print(luas_persegi_panjang)

Input panjang persegi panjang : 29
Input lebar persegi panjang : 12
348.0


# **Numpy**

Numpy merupakan salah satu library dalam python yang memiliki keunggulan dalam perhitungan menggunakan vektor dan matriks dalam berbagai dimensi. Dimulai dengan memanggil library Numpy sebagai berikut : 



In [66]:
import pandas as pd
#ini untuk memanggil numpy

In [68]:
import numpy as np
#ini untuk memanggil numpy juga

# **Perintah Dasar pada Numpy**

In [69]:
a = np.array([0,1,2,3,4,10])
print(a)
#ini merupakan perintah dasar pada numpy 

[ 0  1  2  3  4 10]


In [70]:
a.ndim
#ini untuk mengetahui jumlah barisnya 

1

In [71]:
a.shape
#ini untuk menentukan jumlah kolomnya

(6,)

# **Memanggil Anggota, Kolom dan Baris dengan Numpy**

In [73]:
g = np.array([[2,4,6], [8,10,12], [14,16,18]])
print(g)
#ini untuk menyimpan data dalam array

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [76]:
g[0,2]
#ini menentukan indeksnya

6

In [77]:
g[0,0] = 20
print(g)
#ini untuk mengganti pada posisi indeks kolom 0 baris 0

[[20  4  6]
 [ 8 10 12]
 [14 16 18]]


# **Matriks pada Numpy**

Digunakan untuk membuat berbagai jenis matriks


In [79]:
np.ones((1,3))
#ini untuk membuat 3 kolom dengan posisi 1 di depan

array([[1., 1., 1.]])

In [83]:
a = np.zeroes((10,10))
#ini berarti di library numpynya belum ada

AttributeError: ignored

In [88]:
np.identity(10)
#ini untuk menghasilkan matriks identitas 10x10

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

# **Copy pada Numpy**

ini digunakan untuk mencegah perubahan variabel awal yang tidak dikehendaki maka diperlukan perintah copy seperti yang dijabarkan berikut :

In [89]:
a = np.array([1,2,3,4,5])
print(a)
#mendeklarasikan nilai a terlebih dulu

[1 2 3 4 5]


In [90]:
b = a
print(b)
#ini adalah perintah copy pada numpy untuk meminimalisir kesalahan dalam menyalin
#data yang kita punya agar tidak berubah nantinya

[1 2 3 4 5]


In [92]:
c = b.copy()
print(c)
#ini juga merupakan salah satu cara untuk menyalin data pada b tadi yang 
#sekaligus merupakan data pada a juga 

[1 2 3 4 5]


In [95]:
c[0]=7
print(c)
#ini untuk merubah nilai indeks ke 0 pada data c

[7 2 3 4 5]


In [96]:
print(a)
#disini terlihat data pada a tidak terjadi perubahan apapun

[1 2 3 4 5]


# **Operasi Matematika pada Numpy**

In [97]:
print(a)
#ini masih menggunakan data yang tadi

[1 2 3 4 5]


In [98]:
d = a**2
print(d)
#ini untuk menghasilkan data dalam bentuk pangkat dari data a tadi

[ 1  4  9 16 25]


In [99]:
d = a/2
print(d)
#ini merupakan bentuk pembagian, sama seperti materi sebelumnya
#operasi ini pun nanti berlaku pada penjumlahan dan pengurangan 

[0.5 1.  1.5 2.  2.5]


In [101]:
np.cos(d)
#dapat juga digunakan untuk mencari nilai sin, cos, tan,cosh,tanh,sqrt juga

array([ 0.87758256,  0.54030231,  0.0707372 , -0.41614684, -0.80114362])

In [104]:
print(d)
#nilai d inilah yang akan diproses bukan nilai d di awal tadi

[0.5 1.  1.5 2.  2.5]


In [103]:
np.tan(a)
#data  pada a yang akan diolah, bukan data d

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501])

# **Perkalian Matriks pada Numpy**

perkalian pada matriks harus sesuai dengan aturan perkalian matriks misalnya yaitu perkalian matriks (2x3) dengan matriks (3x4)

In [105]:
#Deklarasikan terlebih dahulu nilai matriksnya
h = np.array([[3,5,7],[4,5,6]])
print(h)

[[3 5 7]
 [4 5 6]]


In [106]:
#Deklarasikan matriks kedua
j = np.array([[2,5,6],[1,4,7]])
print(j)

[[2 5 6]
 [1 4 7]]


In [108]:
k = h*j 
print(k)
#harus diperhatikan dalam penulisan variabel karena jika variabelnya sama dengan
#data sebelumnya maka itu yang akan diproses oleh sistemnya

[[ 6 25 42]
 [ 4 20 42]]


In [112]:
i = np.matmul(a,b)
print(i)
#ini sistem masih menyimpan nilai a dan b pada numpy
#nilainya akan dilupakan jika program direstart

55


In [113]:
print(a)
#ini adalah nilai a yang digunakan pada kode di atas
#nilai b juga sama karena sudah dideskripsikan bahwa b = a

[1 2 3 4 5]


# **Min, Max dan Sum pada Numpy**


sesuai dengan namanya, maka operasi ini digunakan untuk mengetahui nilai tertinggi atau max, terendah atau min dan nilai total atau sum

In [115]:
print(a)
#kita masih memakai data yang sebelumnya

[1 2 3 4 5]


In [116]:
t = np.min(a)
print(t)
#ini adalah perintah mencari nilai min dalam hal ini yaitu pada data a yang
#beranggotakan 1,2,3,4,5

1


In [118]:
y = np.max(a)
print(y)
#sebaliknya, ini adalah perintah untuk mencari nilai maksimum dari data a

5


In [119]:
f = np.max(a,axis =0)
print(f)
#Ini menentukan sumbu di mana rata-rata dihitung. 
#Secara default axis=0. 
#Ini konsisten dengan numpy.mean
#penggunaan ketika axis ditentukan secara eksplisit (in numpy.mean, axis==None 
#secara default, yang menghitung nilai rata-rata di atas larik yang diratakan), 
#di mana axis=0 sepanjang baris (yaitu, indeks dalam numpy), 
#dan axis=1 sepanjang kolom 

5


In [123]:
x = np.sum(a)
print(x)
#ini adalah perintah untuk menentukan jumlah total dari data yang kita punya

15
